"""ROI-relative pseudo forward process and embedding perturbation."""

from __future__ import annotations

import math
from dataclasses import dataclass
from collections.abc import Sequence

import torch

from .rng import cpu_generator


@dataclass(frozen=True)
class PseudoForwardState:
    pseudo_tokens: torch.Tensor
    pseudo_mask: torch.Tensor
    rho_actual: torch.Tensor


def schedule_mask_ratio(
    *, seed: int, mode: str = "cosine", r_min: float = 0.02, r_max: float = 0.98
) -> float:
    """Match the four scheduler transforms used by upstream Meissonic."""
    if not 0 <= r_min <= r_max <= 1:
        raise ValueError("ratio bounds must satisfy 0 <= min <= max <= 1")
    draw = float(torch.rand((), generator=cpu_generator(seed)))
    if mode == "linear":
        ratio = draw
    elif mode == "square":
        ratio = draw**2
    elif mode == "cosine":
        ratio = math.cos(draw * math.pi * 0.5)
    elif mode == "arccos":
        ratio = math.acos(draw) / (math.pi * 0.5)
    else:
        raise ValueError(f"unsupported mask-ratio mode: {mode}")
    return min(r_max, max(r_min, ratio))


def _ratios(rho: float | torch.Tensor | Sequence[float], batch_size: int) -> list[float]:
    if isinstance(rho, torch.Tensor):
        values = rho.detach().cpu().flatten().tolist()
    elif isinstance(rho, (int, float)):
        values = [float(rho)] * batch_size
    else:
        values = [float(item) for item in rho]
    if len(values) != batch_size or any(not 0 <= item <= 1 for item in values):
        raise ValueError("rho must provide one [0,1] ratio per sample")
    return values


def mask_student_prediction(
    student_tokens: torch.Tensor,
    source_tokens: torch.Tensor,
    edit_region_mask: torch.Tensor,
    rho: float | torch.Tensor | Sequence[float],
    mask_token_id: int,
    *,
    seeds: int | Sequence[int],
) -> PseudoForwardState:
    if student_tokens.shape != source_tokens.shape or edit_region_mask.shape != source_tokens.shape:
        raise ValueError("student, source, and ROI token grids must have identical shapes")
    if source_tokens.ndim != 3:
        raise ValueError("token grids must have shape [B,H,W]")
    region = edit_region_mask.bool()
    roi_counts = region.flatten(1).sum(1)
    if (roi_counts == 0).any():
        raise ValueError("every sample must contain editable tokens")
    batch_size = source_tokens.shape[0]
    ratios = _ratios(rho, batch_size)
    if isinstance(seeds, int):
        seeds = [seeds] * batch_size
    else:
        seeds = [int(item) for item in seeds]
    if len(seeds) != batch_size:
        raise ValueError("one pseudo-mask seed is required per sample")

    pseudo = torch.where(region, student_tokens.detach(), source_tokens).clone()
    mask = torch.zeros_like(region)
    for batch, (ratio, seed) in enumerate(zip(ratios, seeds)):
        roi_flat = region[batch].flatten().nonzero(as_tuple=False).flatten().cpu()
        k = max(1, min(roi_flat.numel(), int(round(ratio * roi_flat.numel()))))
        order = torch.randperm(roi_flat.numel(), generator=cpu_generator(seed))
        chosen = roi_flat[order[:k]].to(source_tokens.device)
        mask[batch].view(-1)[chosen] = True
    pseudo[mask] = int(mask_token_id)
    actual = mask.flatten(1).sum(1).to(torch.float32) / roi_counts
    if (mask & ~region).any():
        raise AssertionError("pseudo mask escaped editable ROI")
    if not torch.equal(pseudo[~region], source_tokens[~region]):
        raise RuntimeError("OUTSIDE_REGION_LOCK_VIOLATION")
    return PseudoForwardState(pseudo, mask, actual)


def apply_target_embedding_perturbation(
    hidden_states: torch.Tensor,
    target_embedding_noise: torch.Tensor | None,
    edit_region_mask: torch.Tensor | None,
    sigma: float,
) -> torch.Tensor:
    """Apply the upstream blend formula to target ROI only.

    Expected hidden layout is ``[B,C,H,W]``. Noise is generated by the trainer;
    this function never calls a random API.
    """
    if target_embedding_noise is None or sigma == 0:
        return hidden_states
    if not 0 <= float(sigma) <= 1:
        raise ValueError("embedding perturbation sigma must be in [0,1]")
    if target_embedding_noise.shape != hidden_states.shape:
        raise ValueError("target_embedding_noise must match embedded target states")
    if edit_region_mask is None or tuple(edit_region_mask.shape) != (
        hidden_states.shape[0], hidden_states.shape[2], hidden_states.shape[3]
    ):
        raise ValueError("target embedding perturbation requires a matching ROI mask")
    mask = edit_region_mask.to(device=hidden_states.device, dtype=torch.bool)[:, None]
    noise = target_embedding_noise.to(device=hidden_states.device, dtype=hidden_states.dtype)
    mixed = float(sigma) * noise + math.sqrt(1 - float(sigma) ** 2) * hidden_states
    return torch.where(mask, mixed, hidden_states)
