#!/usr/bin/env python3
"""Export only the pinned official MagicBrush train/dev release, without datasets.

Paths in each manifest are relative to its split directory (--output-root/train
or --output-root/dev), also build_magicbrush_canonical.py's --dataset-root.
Original PNGs are
byte-preserved, including mask_raw. The release's RGBA masks are erased source
images: transparent pixels are editable, not their RGB luminance. mask_edit is
therefore a metadata-free L PNG of 255-alpha, with white=editable. Soft alpha
edges are retained; the canonical builder's existing >0 rule handles binarizing.
No resizing, EXIF rotation, filtering, or turn renumbering is performed.

A completed manifest is published atomically. After interruption, rerun the same
command: every existing asset, manifest and provenance file is checked against
its regenerated bytes and mismatches fail closed. No existing file is replaced.
"""
from __future__ import annotations

import argparse
from collections import Counter
from concurrent.futures import ThreadPoolExecutor
from contextlib import contextmanager
import fcntl
import hashlib
from io import BytesIO
import json
import os
from pathlib import Path
import platform
import re
import tempfile
import zlib

import PIL
from PIL import Image, ImageChops
import pyarrow
import pyarrow.parquet as pq

REVISION = "1d8d4629150d18ca50afab66391866f2085be989"
REPO_ID = "osunlp/MagicBrush"
ROW_COUNTS = {"train": 8807, "dev": 528}
SHARD_COUNTS = {"train": 51, "dev": 4}
COLUMNS = ("img_id", "turn_index", "source_img", "mask_img", "instruction", "target_img")
PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"
MASK_CARD_TEXT = '"mask_img" (str): free-form mask image (white region)'
MASK_POLICY = "alpha mask: L=255-A; grayscale mask: unchanged; white=editable; no threshold"


def json_bytes(value: object) -> bytes:
    return (json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n").encode("utf-8")


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(8 * 1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def safe_directory(path: Path) -> None:
    # Do not follow an existing output-directory symlink on a resumed export.
    for parent in (path, *path.parents):
        if parent.is_symlink():
            raise ValueError(f"Output directory is a symlink: {parent}")
    path.mkdir(parents=True, exist_ok=True)


def publish_bytes(path: Path, data: bytes) -> None:
    """Atomic no-clobber publication; validate bytes even on completed reruns."""
    safe_directory(path.parent)

    def validate() -> None:
        if path.is_symlink() or not path.is_file() or path.read_bytes() != data:
            raise ValueError(f"Existing export bytes differ; refusing overwrite: {path}")

    if path.exists() or path.is_symlink():
        validate()
        return
    # Same-filesystem hard link publishes a fully fsynced file without replace.
    # Unlike rename/replace this remains no-clobber even with concurrent writers.
    with tempfile.NamedTemporaryFile(dir=path.parent, prefix=f".{path.name}.", suffix=".tmp", delete=False) as stream:
        temporary = Path(stream.name)
        try:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
            try:
                os.link(temporary, path)
            except FileExistsError:
                validate()
        finally:
            temporary.unlink(missing_ok=True)


@contextmanager
def export_lock(root: Path):
    safe_directory(root)
    lock = root / ".export.lock"
    if lock.is_symlink():
        raise ValueError(f"Symlink lock refused: {lock}")
    with lock.open("a+b") as stream:
        try:
            fcntl.flock(stream, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError as error:
            raise ValueError(f"Another exporter holds {lock}") from error
        try:
            yield
        finally:
            fcntl.flock(stream, fcntl.LOCK_UN)


def verify_release(snapshot: Path, metadata: Path, split: str) -> dict:
    """Rehash raw bytes against pinned Hub LFS hashes before emitting assets."""
    if split not in ROW_COUNTS:
        raise ValueError("Only official train and dev are allowed; never test")
    release_bytes = metadata.read_bytes()
    release = json.loads(release_bytes)
    if release.get("id") != REPO_ID or release.get("sha") != REVISION:
        raise ValueError("Release metadata does not identify the pinned official release")
    siblings = release["siblings"]
    card_entries = [item for item in siblings if item["rfilename"] == "README.md"]
    if len(card_entries) != 1:
        raise ValueError("Release must identify one dataset card")
    card = (snapshot / "README.md").read_bytes()
    blob = hashlib.sha1(b"blob " + str(len(card)).encode("ascii") + b"\0" + card).hexdigest()
    if blob != card_entries[0]["blobId"] or len(card) != card_entries[0]["size"]:
        raise ValueError("Dataset card release hash mismatch")
    if MASK_CARD_TEXT not in card.decode("utf-8"):
        raise ValueError("Dataset card no longer documents white edit regions")
    card_counts = {item["name"]: item["num_examples"] for item in release["cardData"]["dataset_info"]["splits"]}
    if card_counts.get(split) != ROW_COUNTS[split]:
        raise ValueError(f"Official {split} row count mismatch in release metadata")
    pattern = re.compile(rf"data/{split}-(\d{{5}})-of-(\d{{5}})-[0-9a-f]+\.parquet")
    entries = sorted((item for item in siblings if item["rfilename"].startswith(f"data/{split}-")), key=lambda item: item["rfilename"])
    if len(entries) != SHARD_COUNTS[split] or len({item["rfilename"] for item in entries}) != len(entries):
        raise ValueError(f"Incomplete or duplicated {split} release shard list")
    shards = []
    for index, entry in enumerate(entries):
        name = entry["rfilename"]
        match = pattern.fullmatch(name)
        if not match or int(match[1]) != index or int(match[2]) != SHARD_COUNTS[split]:
            raise ValueError(f"Unexpected shard identity: {name}")
        expected_hash = entry.get("lfs", {}).get("sha256", "")
        if not re.fullmatch(r"[0-9a-f]{64}", expected_hash):
            raise ValueError(f"Missing authoritative LFS SHA256: {name}")
        path = snapshot / name
        if path.stat().st_size != entry["size"] or entry["size"] != entry["lfs"]["size"]:
            raise ValueError(f"Raw release size mismatch: {name}")
        actual_hash = file_sha256(path)
        if actual_hash != expected_hash:
            raise ValueError(f"Raw release SHA256 mismatch: {name}")
        with pq.ParquetFile(path) as parquet:
            schema = parquet.schema_arrow
            if schema.names != list(COLUMNS):
                raise ValueError(f"Unexpected raw columns: {schema.names}")
            for column in ("source_img", "mask_img", "target_img"):
                dtype = schema.field(column).type
                if not pyarrow.types.is_struct(dtype) or [field.name for field in dtype] != ["bytes", "path"]:
                    raise ValueError(f"Expected embedded image bytes/path struct: {column}")
            shards.append({"path": name, "sha256": actual_hash, "bytes": entry["size"], "rows": parquet.metadata.num_rows, "schema": str(schema)})
        print(json.dumps({"event": "raw_shard_verified", "split": split, "shard": name, "rows": shards[-1]["rows"]}), flush=True)
    if sum(item["rows"] for item in shards) != ROW_COUNTS[split]:
        raise ValueError(f"Official {split} Parquet row count mismatch")
    return {"repo_id": REPO_ID, "revision": REVISION, "split": split,
            "expected_rows": ROW_COUNTS[split], "release_metadata_sha256": sha256(release_bytes),
            "card_sha256": sha256(card), "card_git_blob_sha1": blob, "shards": shards}


def identity(row: dict) -> str:
    img_id, turn = row["img_id"], row["turn_index"]
    if not isinstance(img_id, str) or not re.fullmatch(r"[0-9]+", img_id):
        raise ValueError(f"Unsafe or unexpected official img_id: {img_id!r}")
    if type(turn) is not int or turn < 1:
        raise ValueError(f"Expected one-based integer turn_index: {turn!r}")
    if not isinstance(row["instruction"], str) or not row["instruction"].strip():
        raise ValueError("Missing or empty instruction")
    return f"{img_id}_{turn}"


def preflight_rows(snapshot: Path, shards: list[dict]) -> None:
    seen = set()
    for shard in shards:
        with pq.ParquetFile(snapshot / shard["path"]) as parquet:
            for batch in parquet.iter_batches(batch_size=1024, columns=["img_id", "turn_index", "instruction"]):
                for row in batch.to_pylist():
                    key = identity(row)
                    if key in seen:
                        raise ValueError(f"Duplicate sample_key: {key}")
                    seen.add(key)


def deterministic_png(image: Image.Image) -> bytes:
    # New pixel-only image excludes timestamps, EXIF, ICC, text and decoder info.
    if image.mode not in {"1", "L", "LA", "RGB", "RGBA", "I;16"}:
        image = image.convert("RGBA" if "transparency" in image.info else "RGB")
    clean = Image.frombytes(image.mode, image.size, image.tobytes())
    output = BytesIO()
    clean.save(output, format="PNG", compress_level=9, optimize=False)
    return output.getvalue()


def decode_asset(value: dict) -> tuple[bytes, Image.Image, dict]:
    if not isinstance(value, dict) or not isinstance(value.get("bytes"), bytes) or not value["bytes"]:
        raise ValueError("Expected nonempty embedded raw image bytes; path fallback is forbidden")
    raw = value["bytes"]
    with Image.open(BytesIO(raw)) as image:
        if getattr(image, "n_frames", 1) != 1:
            raise ValueError("Multi-frame image is not an official edit image")
        image.load()
        info = {"raw_path": value.get("path"), "raw_sha256": sha256(raw), "raw_bytes": len(raw),
                "raw_format": image.format, "raw_mode": image.mode, "size": list(image.size), "bands": list(image.getbands())}
        is_png = raw.startswith(PNG_SIGNATURE) and image.format == "PNG"
        output = raw if is_png else deterministic_png(image)
        decoded = image.copy()
    info.update({"operation": "preserve_raw_png" if is_png else "decode_to_png_no_geometry_change",
                 "png_sha256": sha256(output), "png_bytes": len(output)})
    return output, decoded, info


def edit_mask(image: Image.Image, original_png: bytes) -> tuple[bytes, dict]:
    """Do not interpret RGBA image luminance as an editing mask."""
    mode = image.mode
    stats = {"raw_mode": mode, "raw_bands": list(image.getbands())}
    if mode in {"RGBA", "LA"}:
        alpha = image.getchannel("A")
        histogram = alpha.histogram()
        mask = alpha.point([255 - value for value in range(256)])
        stats.update({"operation": "inverse_alpha_255_minus_A", "alpha_zero_pixels": histogram[0],
                      "alpha_opaque_pixels": histogram[255], "alpha_partial_pixels": sum(histogram[1:255]),
                      "alpha_distinct_values": sum(count > 0 for count in histogram)})
        output = deterministic_png(mask)
    elif mode in {"1", "L", "RGB"}:
        if mode == "RGB":
            r, g, b = image.split()
            if ImageChops.difference(r, g).getbbox() or ImageChops.difference(r, b).getbbox():
                raise ValueError("Ambiguous colored mask without alpha; refusing luminance guess")
        mask = image.convert("L")
        output = original_png
        stats["operation"] = "preserve_white_edit_grayscale_png"
    else:
        raise ValueError(f"Unsupported official mask mode: {mode}")
    histogram = mask.histogram()
    total = mask.width * mask.height
    stats.update({"mask_semantics": "edit_region", "polarity": "white_editable", "pixels": total,
                  "editable_pixels_gt0": total - histogram[0], "white_pixels": histogram[255],
                  "soft_edge_pixels": sum(histogram[1:255]), "region_fraction_gt0": (total - histogram[0]) / total,
                  "raw_luminance_gt0_fraction": 1 - image.convert("L").histogram()[0] / total})
    return output, stats


def export_row(raw: dict, *, split: str, shard: dict, row_in_shard: int, index: int, output: Path) -> dict:
    key = identity(raw)
    row = {"sample_key": key, "img_id": raw["img_id"], "turn_index": raw["turn_index"],
           "instruction": raw["instruction"], "split": split, "mask_semantics": "edit_region"}
    assets = {}
    for name, column in (("source", "source_img"), ("target", "target_img"), ("mask_raw", "mask_img")):
        data, image, info = decode_asset(raw[column])
        relative = f"images/{key}/{name}.png"
        publish_bytes(output / split / relative, data)
        row[name], row[f"{name}_sha256"] = relative, sha256(data)
        assets[column] = info
        if name == "mask_raw":
            derived, stats = edit_mask(image, data)
            row["mask_edit"] = f"images/{key}/mask_edit.png"
            row["mask_edit_sha256"] = sha256(derived)
            row["mask_provenance"] = stats
            publish_bytes(output / split / row["mask_edit"], derived)
        image.close()
    row["raw_provenance"] = {"revision": REVISION, "parquet": shard["path"], "parquet_sha256": shard["sha256"],
                             "row_in_shard": row_in_shard, "split_row_index": index, "assets": assets}
    return row


def archive_common_root_v1(root: Path, archive_root: Path, release: dict) -> dict:
    """Explicit opt-in metadata migration; archive bytes outside the dataset tree.

    All old metadata is validated and copied before removing any old active file.
    A crash during removal is resumable using the archived copy; PNGs are never
    moved or changed. The normal exporter then rederives and compares every PNG.
    """
    archive_root = Path(archive_root).absolute()
    dataset_root = root.parent.resolve()
    if archive_root.resolve() == dataset_root or dataset_root in archive_root.resolve().parents:
        raise ValueError("Legacy archive must be outside the dataset tree")
    archive = archive_root / release["split"]
    safe_directory(archive)
    names = ("export_provenance.json", "manifest.jsonl", "export_summary.json")
    legacy = {}
    for name in names:
        old = archive / name
        active = root / name
        path = old if old.exists() else active
        if path.is_symlink() or not path.is_file():
            raise ValueError(f"Migration requires complete legacy metadata: {path}")
        legacy[name] = path.read_bytes()
    provenance = json.loads(legacy["export_provenance.json"])
    summary = json.loads(legacy["export_summary.json"])
    if provenance.get("schema_version") != 1 or provenance.get("manifest_path_base") != "output_root":
        raise ValueError("Migration source is not common-root exporter v1")
    if provenance.get("release") != release or provenance.get("mask_policy") != MASK_POLICY:
        raise ValueError("Legacy release or mask policy does not match verified raw release")
    if (summary.get("status") != "complete" or summary.get("rows") != release["expected_rows"]
            or summary.get("split") != release["split"]
            or summary.get("manifest_sha256") != sha256(legacy["manifest.jsonl"])
            or summary.get("provenance_sha256") != sha256(legacy["export_provenance.json"])):
        raise ValueError("Legacy metadata hashes/counts do not verify")
    rows = [json.loads(line) for line in legacy["manifest.jsonl"].splitlines()]
    if len(rows) != release["expected_rows"]:
        raise ValueError("Legacy manifest row count mismatch")
    for row in rows:
        key = identity(row)
        for name in ("source", "target", "mask_raw", "mask_edit"):
            if row[name] != f"{release['split']}/images/{key}/{name}.png":
                raise ValueError("Legacy manifest paths do not match the v1 contract")
    for name in names:
        publish_bytes(archive / name, legacy[name])
    # Provenance is removed last so interruption during other removals cannot be
    # mistaken for a finished v2 run. Never remove already-regenerated v2 files.
    active_provenance = root / "export_provenance.json"
    is_v2 = active_provenance.is_file() and json.loads(active_provenance.read_bytes()).get("schema_version") == 2
    if not is_v2:
        for name in ("export_summary.json", "manifest.jsonl", "export_provenance.json"):
            path = root / name
            if path.exists() or path.is_symlink():
                if path.is_symlink() or path.read_bytes() != legacy[name]:
                    raise ValueError(f"Active legacy metadata differs; refusing removal: {path}")
                path.unlink()
    return {"from_schema_version": 1, "to_schema_version": 2,
            "archived_metadata_sha256": {name: sha256(data) for name, data in legacy.items()}}


def export_split(snapshot: Path, metadata: Path, output: Path, split: str, *, workers: int = 4,
                 migrate_common_root_v1: Path | None = None) -> dict:
    if split not in ROW_COUNTS:
        raise ValueError("Only official train and dev are allowed; never test")
    if workers < 1 or workers > 16:
        raise ValueError("workers must be between 1 and 16")
    snapshot, metadata = Path(snapshot).resolve(), Path(metadata).resolve()
    # Check output symlinks before resolve, including the selected split.
    output = Path(output).absolute()
    if snapshot == output.resolve() or snapshot in output.resolve().parents:
        raise ValueError("Output must not modify the raw snapshot")
    safe_directory(output / split)
    with export_lock(output / split):
        release = verify_release(snapshot, metadata, split)
        preflight_rows(snapshot, release["shards"])
        migration_path = output / split / "export_migration.json"
        if migrate_common_root_v1 is not None:
            migration = archive_common_root_v1(output / split, migrate_common_root_v1, release)
            publish_bytes(migration_path, json_bytes(migration))
        provenance = {"schema_version": 2, "release": release, "mask_policy": MASK_POLICY,
                      "manifest_path_base": "split_root", "order": "lexical shard then physical Parquet row",
                      "sample_key_policy": "original img_id + '_' + one-based original turn_index",
                      "exporter_sha256": file_sha256(Path(__file__)),
                      "runtime": {"python": platform.python_version(), "pillow": PIL.__version__,
                                  "pyarrow": pyarrow.__version__, "zlib": zlib.ZLIB_RUNTIME_VERSION}}
        if migration_path.exists():
            provenance["migration_sha256"] = file_sha256(migration_path)
        publish_bytes(output / split / "export_provenance.json", json_bytes(provenance))
        records = []
        with ThreadPoolExecutor(max_workers=workers) as pool:
            for shard in release["shards"]:
                shard_offset = 0
                with pq.ParquetFile(snapshot / shard["path"]) as parquet:
                    for batch in parquet.iter_batches(batch_size=workers * 2, columns=list(COLUMNS)):
                        raw_rows = batch.to_pylist()
                        futures = [pool.submit(export_row, raw, split=split, shard=shard,
                                               row_in_shard=shard_offset + offset, index=len(records) + offset, output=output)
                                   for offset, raw in enumerate(raw_rows)]
                        records.extend(future.result() for future in futures)
                        shard_offset += len(raw_rows)
                if shard_offset != shard["rows"]:
                    raise ValueError(f"Parquet row count changed during export: {shard['path']}")
                print(json.dumps({"event": "shard_exported", "split": split, "rows": len(records), "shard": shard["path"]}), flush=True)
        if len(records) != ROW_COUNTS[split]:
            raise ValueError(f"Exported {split} count differs from official release")
        manifest = b"".join(json_bytes(record) for record in records)
        raw_modes = Counter(record["mask_provenance"]["raw_mode"] for record in records)
        operations = Counter(record["mask_provenance"]["operation"] for record in records)
        formats = Counter(info["raw_format"] for record in records for info in record["raw_provenance"]["assets"].values())
        summary = {"status": "complete", "split": split, "rows": len(records),
                   "groups": len({record["img_id"] for record in records}), "revision": REVISION,
                   "manifest": "manifest.jsonl", "manifest_sha256": sha256(manifest),
                   "provenance_sha256": sha256(json_bytes(provenance)), "raw_mask_modes": dict(raw_modes),
                   "mask_operations": dict(operations), "raw_image_formats": dict(formats),
                   "empty_edit_masks": sum(record["mask_provenance"]["editable_pixels_gt0"] == 0 for record in records),
                   "full_edit_masks": sum(record["mask_provenance"]["region_fraction_gt0"] == 1 for record in records),
                   "source_target_size_mismatches": sum(record["raw_provenance"]["assets"]["source_img"]["size"] != record["raw_provenance"]["assets"]["target_img"]["size"] for record in records)}
        publish_bytes(output / split / "manifest.jsonl", manifest)
        # This marker is last: a manifest without it is not a completed export.
        publish_bytes(output / split / "export_summary.json", json_bytes(summary))
        print(json.dumps(summary, sort_keys=True), flush=True)
        return summary


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--snapshot-root", required=True, type=Path)
    parser.add_argument("--release-metadata", required=True, type=Path, help="Hash-bearing Hub API response for the fixed revision")
    parser.add_argument("--output-root", required=True, type=Path, help="RUN_ROOT/derived/magicbrush; canonical roots are its train/dev subdirectories")
    parser.add_argument("--split", nargs="+", required=True, choices=("train", "dev"))
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--migrate-common-root-v1", type=Path, metavar="ARCHIVE_ROOT",
                        help="Explicitly archive completed v1 metadata outside dataset tree, then revalidate all assets and publish v2 split-relative paths")
    args = parser.parse_args()
    if len(set(args.split)) != len(args.split):
        parser.error("Duplicate splits are not allowed")
    for split in args.split:
        export_split(args.snapshot_root, args.release_metadata, args.output_root, split, workers=args.workers,
                     migrate_common_root_v1=args.migrate_common_root_v1)


if __name__ == "__main__":
    main()
