#!/usr/bin/env bash
set -euo pipefail

script_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
actual_root="$(git -C "$script_root" rev-parse --show-toplevel)"
EXPECTED_WORKTREE="${EDITMGT_WORKTREE:-$actual_root}"
if [[ "$(realpath "$actual_root")" != "$(realpath "$EXPECTED_WORKTREE")" ]]; then
  echo "WRONG_WORKTREE expected=$EXPECTED_WORKTREE actual=$actual_root" >&2
  exit 2
fi

ensure_short_tmpdir() {
  local current_tmp="${TMPDIR:-}"
  local user_slug="${USER:-user}"
  local job_slug="${SLURM_JOB_ID:-local}"
  if [[ -z "$current_tmp" || ${#current_tmp} -gt 80 ]]; then
    current_tmp="/tmp/editmgt-${user_slug}-${job_slug}-$$"
  fi
  mkdir -p "$current_tmp"
  export TMPDIR="$current_tmp"
  export TMP="$current_tmp"
  export TEMP="$current_tmp"
}

pick_main_process_port() {
  if [[ -n "${EDITMGT_MAIN_PROCESS_PORT:-}" ]]; then
    if [[ ! "$EDITMGT_MAIN_PROCESS_PORT" =~ ^[0-9]+$ ]] \
      || (( EDITMGT_MAIN_PROCESS_PORT < 1 || EDITMGT_MAIN_PROCESS_PORT > 65535 )); then
      echo "invalid EDITMGT_MAIN_PROCESS_PORT" >&2
      return 2
    fi
    printf '%s\n' "$EDITMGT_MAIN_PROCESS_PORT"
    return
  fi
  local python_bin="${UV_PROJECT_ENVIRONMENT:+$UV_PROJECT_ENVIRONMENT/bin/python}"
  python_bin="${python_bin:-python}"
  "$python_bin" - <<'PY'
import socket
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
    sock.bind(("127.0.0.1", 0))
    print(sock.getsockname()[1])
PY
}

ensure_short_tmpdir
cd "$actual_root"
if [[ -n "${ASSET_ROOT:-}" && -f "$ASSET_ROOT/artifacts/formal_env.sh" ]]; then
  # Generated by run_formal_prepare.sh; paths are shell-escaped by the generator.
  source "$ASSET_ROOT/artifacts/formal_env.sh"
fi
