#!/usr/bin/env bash
set -euo pipefail

script_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
actual_root="$(git -C "$script_root" rev-parse --show-toplevel)"
EXPECTED_WORKTREE="${EDITMGT_WORKTREE:-$actual_root}"
if [[ "$(realpath "$actual_root")" != "$(realpath "$EXPECTED_WORKTREE")" ]]; then
  echo "WRONG_WORKTREE expected=$EXPECTED_WORKTREE actual=$actual_root" >&2
  exit 2
fi
cd "$actual_root"
if [[ -n "${ASSET_ROOT:-}" && -f "$ASSET_ROOT/artifacts/formal_env.sh" ]]; then
  # Generated by run_formal_prepare.sh; paths are shell-escaped by the generator.
  source "$ASSET_ROOT/artifacts/formal_env.sh"
fi
